" Zyst

" DO NOT EDIT THIS FILE DIRECTLY
" This is a file generated from a literate programing source file located at
" https://github.com/Zyst/dotfiles/blob/master/vimrc.org
" You should make any changes there and regenerate it from Emacs org-mode using C-c C-v t

if !exists("g:os")
    if has("win64") || has("win32") || has("win16")
        let g:os = "Windows"
    else
        let g:os = substitute(system('uname'), '\n', '', '')
    endif
endif

if !(g:os == "Windows")
  if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif
endif

if has('nvim')
  call plug#begin('~/.config/nvim/plugged')
      Plug 'nvim-orgmode/orgmode'
      Plug 'nvim-lua/plenary.nvim'
      Plug 'lewis6991/gitsigns.nvim'
      Plug 'nvim-treesitter/nvim-treesitter', {'branch': 'main', 'do': ':TSUpdate'}
      Plug 'hrsh7th/nvim-cmp'
      Plug 'hrsh7th/cmp-nvim-lsp'
      Plug 'hrsh7th/cmp-nvim-lua'
      Plug 'hrsh7th/cmp-buffer'
      Plug 'hrsh7th/cmp-path'
      Plug 'hrsh7th/cmp-calc'
      Plug 'hrsh7th/cmp-emoji'
      Plug 'L3MON4D3/LuaSnip', { 'do': 'make install_jsregexp' }
      Plug 'saadparwaiz1/cmp_luasnip'
      Plug 'neovim/nvim-lspconfig'
      Plug 'williamboman/mason.nvim'
      Plug 'williamboman/mason-lspconfig.nvim'
      Plug 'Olical/conjure'
else
  call plug#begin('~/.vim/plugged')
      
endif

" Plug 'Zyst/egoist-one.vim'
" Plug 'sainnhe/edge'
" Plug 'sainnhe/everforest'
Plug 'rebelot/kanagawa.nvim'
" Plug 'rose-pine/neovim', { 'as': 'rose-pine' }
" Plug 'savq/melange'
Plug 'ap/vim-css-color'
Plug 'nvim-lualine/lualine.nvim'
Plug 'tpope/vim-fugitive'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'gfanto/fzf-lsp.nvim'
Plug 'nvim-tree/nvim-tree.lua'
Plug 'editorconfig/editorconfig-vim'
Plug 'tpope/vim-projectionist'
Plug 'stevearc/conform.nvim'
Plug 'windwp/nvim-autopairs'
Plug 'mattn/emmet-vim'
let g:polyglot_disabled = ['org']
Plug 'sheerun/vim-polyglot'
Plug 'dmix/elvish.vim', { 'on_ft': ['elvish']}
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-dispatch'
Plug 'vim-test/vim-test'
Plug 'christoomey/vim-tmux-navigator'
Plug 'folke/which-key.nvim'

call plug#end()

let mapleader="\<Space>"

let maplocalleader=","

nnoremap <Leader><Leader> <C-^>

nnoremap <Leader>o :only<CR>

nnoremap <Leader>w :w<CR>

nnoremap <Leader>q :q<CR>

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

nnoremap <Tab> za

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" nnoremap <C-m> <C-w>h
" nnoremap <C-n> <C-w>j
" nnoremap <C-e> <C-w>k
" nnoremap <C-i> <C-w>l

nmap <Esc><Esc> :noh<CR><Esc>

nnoremap <Leader>ev :vsp ~/.vimrc<CR>

nnoremap <Leader>er :source $MYVIMRC<Bar>echo "Nvim config reloaded!"<CR>

xnoremap <C-h> <C-w>h
xnoremap <C-j> <C-w>j
xnoremap <C-k> <C-w>k
xnoremap <C-l> <C-w>l

" xnoremap <C-m> <C-w>h
" xnoremap <C-n> <C-w>j
" xnoremap <C-e> <C-w>k
" xnoremap <C-i> <C-w>l

vnoremap <S-j> :m '>+1<CR>gv=gv
vnoremap <S-k> :m '<-2<CR>gv=gv

tnoremap <Esc> <C-\><C-n>

tnoremap <M-[> <Esc>

set nomodeline

filetype indent plugin on

set clipboard+=unnamedplus

set number

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,WinEnter * if &nu | set rnu   | endif
  autocmd BufLeave,FocusLost,WinLeave   * if &nu | set nornu | endif
augroup END

autocmd BufRead,BufNewFile *.jjdescription setfiletype jjdescription

autocmd BufReadPost,BufNewFile *.org set filetype=org

set hidden

augroup myvimrc
  au!
  au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END

set backspace=indent,eol,start

set foldenable
set foldmethod=indent
set foldlevelstart=10

" set foldlevelstart=1

set autoindent

set smartindent

scriptencoding utf-8
set encoding=utf-8
set fileencoding=utf-8

set cursorline

set expandtab

set undofile
set undodir=~/.vim/undo_files//
set directory=~/.vim/swap_files//

set laststatus=2

set lazyredraw

set linebreak
let &showbreak='↳ '

set scrolloff=1

set tabstop=2
set softtabstop=2

set shiftround
set shiftwidth=2

set splitbelow
set splitright

set wrap
set textwidth=0

set showmatch

set incsearch

set ignorecase
set smartcase

set visualbell

set ttyfast

set hlsearch

set nobackup
set nowritebackup

set signcolumn=yes

if g:os == "Linux"
    
endif

if g:os == "Windows"
    
endif

if g:os == "Darwin"
    
endif

if (g:os == "Linux") || (g:os == "Darwin")
    
endif

lua << EOF
require('orgmode').setup()
EOF

if (has("termguicolors"))
  set termguicolors
endif

syntax on

function g:HighlightEcho ()
  " Echo under mouse
  echom synIDattr(synID(line("."),col("."),1),"name")

  " Echo full group
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunction

" colorscheme onedark

" let g:onedark_terminal_italics=1

" let g:edge_enable_italic = 1

" colorscheme edge

" let g:everforest_enable_italic = 1

" colorscheme everforest

colorscheme kanagawa-dragon

" colorscheme rose-pine-moon

" colorscheme melange

lua << EOF
require('lualine').setup({
  options = {
    icons_enabled = false,
    theme = 'auto',
    section_separators = '',
    component_separators = '',
  },
  sections = {
    lualine_a = { 'mode' },
    lualine_b = {},
    lualine_c = { 'filename' },
    lualine_x = { 'diff', 'diagnostics' },
    lualine_y = {},
    lualine_z = {},
  },
})
EOF

lua <<EOF
  require('gitsigns').setup {
    current_line_blame = false,
    on_attach = function(bufnr)
      local gs = package.loaded.gitsigns

      local function map(mode, l, r, opts)
        opts = opts or {}
        opts.buffer = bufnr
        vim.keymap.set(mode, l, r, opts)
      end

      -- Navigation
      map('n', ']c', function()
        if vim.wo.diff then return ']c' end
        vim.schedule(function() gs.next_hunk() end)
        return '<Ignore>'
      end, {expr=true})

      map('n', '[c', function()
        if vim.wo.diff then return '[c' end
        vim.schedule(function() gs.prev_hunk() end)
        return '<Ignore>'
      end, {expr=true})

      -- Actions
      map({'n', 'v'}, '<leader>hs', ':Gitsigns stage_hunk<CR>')
      map({'n', 'v'}, '<leader>hr', ':Gitsigns reset_hunk<CR>')
      map('n', '<leader>hS', gs.stage_buffer)
      map('n', '<leader>hu', gs.undo_stage_hunk)
      map('n', '<leader>hR', gs.reset_buffer)
      map('n', '<leader>hp', gs.preview_hunk)
      map('n', '<leader>hd', gs.diffthis)
      map('n', '<leader>hD', function() gs.diffthis('~') end)
      map('n', '<leader>td', gs.toggle_deleted)

      -- Text object
      map({'o', 'x'}, 'ih', ':<C-U>Gitsigns select_hunk<CR>')
    end
  }
EOF

nnoremap gad :G add %<CR>

nnoremap gac :G commit<CR>

nnoremap <Leader>t :Files<cr>
nnoremap <Leader>b :Buffers<cr>
nnoremap <Leader>s :BLines<cr>
nnoremap <Leader>S :Rg <cr>
nnoremap <Leader>g :GFiles?<cr>
nnoremap gr :References<cr>
nnoremap <Leader>ed :Diagnostics<cr>
nnoremap <Leader>eD :DiagnosticsAll<cr>

nnoremap gh :lua vim.diagnostic.open_float()<cr>
nnoremap gH :lua vim.diagnostic.setloclist()<cr>

let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-s': 'split',
  \ 'ctrl-v': 'vsplit' }

let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.8 } }

set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --follow

if executable('rg')
  let g:rg_derive_root='true'
endif

lua << EOF
require('nvim-tree').setup({
  renderer = {
    icons = {
      show = {
        file   = false,   -- no per-file icons (no =nvim-web-devicons= dep)
        folder = false,   -- no folder glyphs either
      },
      web_devicons = {
        file   = { enable = false },
        folder = { enable = false },
      },
      glyphs = {
        git = {
          unstaged  = '│',
          staged    = '│',
          unmerged  = '│',
          renamed   = '│',
          untracked = '│',
          deleted   = '│',
          ignored   = '│',
        },
      },
    },
    highlight_git = 'icon',   -- tint the bar only; filename stays neutral
    indent_markers = { enable = true },
    special_files = {},       -- no bold highlight on README.md / Makefile / etc.
  },
  filters = { dotfiles = false },
  diagnostics = { enable = true },
  git = { enable = true },
  actions = {
    remove_file = {
      close_window = false,  -- keep the window holding the deleted file; let nvim fall back to a previous buffer
    },
  },
  on_attach = function(bufnr)
    local api = require('nvim-tree.api')
    api.config.mappings.default_on_attach(bufnr)
    -- Restore vim natives by removing nvim-tree's overrides
    for _, lhs in ipairs({
      'f', 'F',                        -- find char / backward find char
      's', 'S',                        -- substitute char / line
      'J', 'K',                        -- join lines / lookup under cursor
      'R',                             -- replace mode
      'Y',                             -- yank line
      '<C-]>', '<C-r>', '<C-t>',       -- tag jump / redo / pop tag
      '<C-x>', '<C-v>', '<C-e>',       -- decrement / visual-block / scroll
    }) do
      pcall(vim.keymap.del, 'n', lhs, { buffer = bufnr })
    end
  end,
})

-- nvim-tree highlight overrides:
--   - Match the gitsigns gutter palette: copy only the fg color from each =GitSigns*=
--     group onto the corresponding =NvimTreeGit*Icon=, leaving bg unset so the bar
--     blends with the tree row (resting and cursor-highlighted).
--   - Clear =NvimTreeExecFile= so files with the exec bit don't render green;
--     we don't need that signal in the tree.
-- Re-applied on ColorScheme so colorscheme switches keep the overrides.
local function nvim_tree_apply_hl_overrides()
  local mapping = {
    NvimTreeGitDirtyIcon   = 'GitSignsChange',
    NvimTreeGitDeletedIcon = 'GitSignsDelete',
    NvimTreeGitNewIcon     = 'GitSignsUntracked',
    NvimTreeGitStagedIcon  = 'GitSignsStagedAdd',
    NvimTreeGitRenamedIcon = 'GitSignsChange',
    NvimTreeGitMergeIcon   = 'GitSignsDelete',
    NvimTreeGitIgnoredIcon = 'Comment',
  }
  for target, source in pairs(mapping) do
    local src = vim.api.nvim_get_hl(0, { name = source, link = false })
    if src.fg then
      vim.api.nvim_set_hl(0, target, { fg = src.fg })
    end
  end
  vim.api.nvim_set_hl(0, 'NvimTreeExecFile', {})
end
nvim_tree_apply_hl_overrides()
vim.api.nvim_create_autocmd('ColorScheme', { callback = nvim_tree_apply_hl_overrides })

-- Smart-toggle: close only if cursor is in the tree, otherwise focus + reveal current file.
function _G.NvimTreeSmartToggle()
  local api = require('nvim-tree.api')
  if vim.bo.filetype == 'NvimTree' then
    api.tree.close()
  else
    api.tree.find_file({ open = true, focus = true })
  end
end
EOF

nnoremap <Leader>n <Cmd>lua NvimTreeSmartToggle()<CR>

let g:projectionist_heuristics = {
\   '*': {
\     '*.c': {
\       'alternate': '{}.h',
\       'type': 'source'
\     },
\     '*.h': {
\       'alternate': '{}.c',
\       'type': 'header'
\     },
\
\   }
\ }

" Helper function for batch-updating the g:projectionist_heuristics variable.
function! s:project(...)
  for [l:pattern, l:projection] in a:000
    let g:projectionist_heuristics['*'][l:pattern] = l:projection
  endfor
endfunction

" Set up projections for JS variants.
for s:extension in ['.js', '.jsx', '.ts', '.tsx']
  call s:project(
        \ ['*' . s:extension, {
        \   'alternate': [
        \     '{dirname}/{basename}.test' . s:extension,
        \     '{dirname}/__tests__/{basename}-test' . s:extension,
        \     '{dirname}/__tests__/{basename}.test' . s:extension,
        \     '{dirname}/__tests__/{basename}.test.js',
        \   ],
        \   'type': 'source'
        \ }],
        \ ['*.test' . s:extension, {
        \   'alternate': '{basename}' . s:extension,
        \   'type': 'test',
        \ }],
        \ ['**/__tests__/*-test' . s:extension, {
        \   'alternate': '{dirname}/{basename}' . s:extension,
        \   'type': 'test'
        \ }],
        \ ['**/__tests__/*.test' . s:extension, {
        \   'alternate': [
        \     '{dirname}/{basename}' . s:extension,
        \     '{dirname}/{basename}.tsx',
        \     '{dirname}/{basename}.ts',
        \     '{dirname}/{basename}.js',
        \     '{dirname}/{basename}.jsx',
        \    ],
        \   'type': 'test'
        \ }])
endfor

nnoremap <Leader>a :A<CR>

lua <<EOF
require('nvim-treesitter').install({
  'bash', 'c', 'clojure', 'css', 'diff', 'fish', 'go',
  'html', 'javascript', 'json', 'lua', 'markdown', 'markdown_inline',
  'nix', 'python', 'query', 'rust', 'toml', 'tsx', 'typescript',
  'vim', 'vimdoc', 'yaml',
})

vim.api.nvim_create_autocmd("FileType", {
  callback = function() pcall(vim.treesitter.start) end,
})
EOF

set completeopt=menuone,noselect

lua <<EOF
local cmp = require('cmp')
local luasnip = require('luasnip')

local lsp_kinds = {
  Class = ' ',
  Color = ' ',
  Constant = ' ',
  Constructor = ' ',
  Enum = ' ',
  EnumMember = ' ',
  Event = ' ',
  Field = ' ',
  File = ' ',
  Folder = ' ',
  Function = ' ',
  Interface = ' ',
  Keyword = ' ',
  Method = ' ',
  Module = ' ',
  Operator = ' ',
  Property = ' ',
  Reference = ' ',
  Snippet = ' ',
  Struct = ' ',
  Text = ' ',
  TypeParameter = ' ',
  Unit = ' ',
  Value = ' ',
  Variable = ' ',
}

cmp.setup({
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body)
    end,
  },

  mapping = cmp.mapping.preset.insert({
    ['<C-b>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-e>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = false }),
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end, { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, { 'i', 's' }),
  }),

  formatting = {
    format = function(entry, vim_item)
      vim_item.kind = string.format('%s %s', lsp_kinds[vim_item.kind], vim_item.kind)
      vim_item.menu = ({
        nvim_lsp = '[LSP]',
        nvim_lua = '[Lua]',
        luasnip = '[Snip]',
        buffer = '[Buf]',
        path = '[Path]',
        calc = '[Calc]',
        emoji = '[Emoji]',
      })[entry.source.name]
      return vim_item
    end,
  },

  completion = {
    completeopt = 'menu,menuone,noinsert',
  },

  window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  },

  sources = cmp.config.sources({
    { name = 'luasnip' },
    { name = 'nvim_lsp' },
    { name = 'nvim_lua' },
    { name = 'buffer' },
    { name = 'calc' },
    { name = 'emoji' },
    { name = 'path' },
  }),
})
EOF

lua <<EOF
local servers = {
  'bashls',
  'clojure_lsp',
  'cssls',
  'gopls',
  'html',
  'jsonls',
  'lua_ls',
  'nixd',
  'pyright',
  'rust_analyzer',
  'ts_ls',
  'yamlls',
}

-- nixd isn't in mason's registry, so we install it via home-manager
-- (=pkgs.nixd= in common.nix) and skip it in mason-lspconfig's ensure_installed.
-- Everything else comes from mason.
local mason_servers = vim.tbl_filter(function(s) return s ~= 'nixd' end, servers)

require('mason').setup()
require('mason-lspconfig').setup({ ensure_installed = mason_servers })

local capabilities = vim.lsp.protocol.make_client_capabilities()
local has_cmp_nvim_lsp, cmp_nvim_lsp = pcall(require, 'cmp_nvim_lsp')
if has_cmp_nvim_lsp then
  capabilities = cmp_nvim_lsp.default_capabilities(capabilities)
end

vim.lsp.config('*', { capabilities = capabilities })
vim.lsp.enable(servers)
EOF

lua << EOF
require('conform').setup({
  formatters_by_ft = {
    ['*'] = { 'trim_whitespace', 'trim_newlines' },
    javascript = { 'prettier', 'eslint_d' },
    typescript = { 'prettier', 'eslint_d' },
    typescriptreact = { 'prettier', 'eslint_d' },
    css = { 'prettier' },
    scss = { 'prettier' },
    html = { 'prettier' },
    json = { 'prettier' },
  },
})
EOF

lua << EOF
vim.keymap.set('n', '<Leader>f', function()
  require('conform').format({ async = false, lsp_format = 'fallback' })
end)
EOF

lua << EOF
require('nvim-autopairs').setup({})
local cmp = require('cmp')
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done())
EOF

let g:user_emmet_expandabbr_key = '<C-e>'

let g:dispatch_tmux_height = '50% -h'

let test#strategy = "neovim"
let test#neovim#term_position = "vert"

nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>

" nnoremap <silent> {C-m} :TmuxNavigateLeft<cr>
" nnoremap <silent> {C-n} :TmuxNavigateDown<cr>
" nnoremap <silent> {C-e} :TmuxNavigateUp<cr>
" nnoremap <silent> {C-i} :TmuxNavigateRight<cr>

set timeoutlen=500

lua << EOF
  require('which-key').setup {}
EOF

lua << EOF
local wk = require('which-key')

wk.add({
  { 't', group = 'test' },
  { 't<C-n>', desc = 'Test Nearest' },
  { 't<C-f>', desc = 'Test File' },
  { 't<C-s>', desc = 'Test Suite' },
  { 't<C-l>', desc = 'Test Last' },
  { 't<C-g>', desc = 'Test Visit' },
})
EOF
