#!/usr/bin/env sh

# Custom space names
yabai -m space 1 --label main
yabai -m space 2 --label code
yabai -m space 3 --label three
yabai -m space 4 --label browser
yabai -m space 5 --label five
yabai -m space 6 --label organize
yabai -m space 7 --label seven
yabai -m space 8 --label eight
yabai -m space 9 --label nine
yabai -m space 10 --label ten
yabai -m space 11 --label eleven
yabai -m space 12 --label twelve
yabai -m space 13 --label thirteen
yabai -m space 14 --label fourteen
yabai -m space 15 --label fifteen
yabai -m space 16 --label sixteen
yabai -m space 17 --label seventeen
yabai -m space 18 --label eighteen

# Labels for windows we don't want yabai to manage (floating by default)
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^qemu-system-aarch64$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^TeamViewer$" sticky=off layer=above manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^perl_client_app$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^CiscoSparkHelper$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Cisco Webex Start$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off


## Some random global settings
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0

## WITH SIP ENABLED (Installed Limelight seperately, Don't need this)
yabai -m config window_border off

## Utilities
# Makes it so that new windows take a smaller % of the screen, if on, yabai rebalances the screens
yabai -m config auto_balance off
# Makes new windows take 50% of screen
yabai -m config split_ratio 0.50
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2
yabai -m config window_gap 10

#Limelight addon (Kill it and start it each time Yabai starts)
killall limelight &>/dev/null
limelight &>/dev/null &

echo "yabai configuration loaded.."

#END
